In [ ]:
# 第 8 章 数据规整:聚合、合并和重 塑
# 是为了处理

In [9]:
import pandas as pd
import numpy as np
# 将维度变高了
data = pd.Series(np.random.randn(9),index=[['a', 'a', 'a', 'b', 'b', 'c', 'c','d', 'd'], [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -0.171981
   2   -1.493067
   3    0.597870
b  1   -0.114285
   3    1.567337
c  1   -2.076967
   2    0.345554
d  2    0.492373
   3    2.092818
dtype: float64

In [10]:
data['b']

1   -0.114285
3    1.567337
dtype: float64

In [11]:
data.loc[:, 2]

a   -1.493067
c    0.345554
d    0.492373
dtype: float64

In [12]:
data.unstack()

1         2         3
a -0.171981 -1.493067  0.597870
b -0.114285       NaN  1.567337
c -2.076967  0.345554       NaN
d       NaN  0.492373  2.092818

In [15]:
data.unstack()

1         2         3
a -0.171981 -1.493067  0.597870
b -0.114285       NaN  1.567337
c -2.076967  0.345554       NaN
d       NaN  0.492373  2.092818

In [16]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1,2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])

In [17]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [18]:
frame['Ohio']

Green  Red
a 1      0    1
  2      3    4
b 1      6    7
  2      9   10

In [19]:
frame.index.names = ['key1', 'key2']

In [20]:
frame.columns.names = ['state', 'color']

In [21]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [22]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [23]:
frame.swaplevel('key1', 'key2')


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [24]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [25]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [26]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [27]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [28]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two',
'two', 'two', 'two'],'d': [0, 1, 2, 0, 1, 2, 3]})

In [29]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [30]:
# 将其中的某些列变成索引
frame2 = frame.set_index(['c', 'd'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [31]:
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [32]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [33]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a','b'],'data1': range(7)})


In [34]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [35]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

In [36]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [37]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [38]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [40]:
# 如果两个对象的列名不同，也可以分别进行指定:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a',
'b'],                'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
            'data2': range(3)})
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [41]:
pd.merge(df1, df2, how='outer')
# 交集并集说的是里面的数据

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [42]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.],
[16., 17.]],index=['a', 'c', 'e', 'f'],columns=['New York',
'Oregon'])

In [43]:
another

New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [44]:
left2.join([right2, another])

NameError: name 'left2' is not defined

In [45]:
arr = np.arange(12).reshape((3, 4))

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [48]:
s1 = pd.Series([0, 1], index=['a', 'b'])

In [49]:
s1

a    0
b    1
dtype: int64

In [50]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])


In [51]:
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [54]:
pd.concat([s1, s2, s3], axis=1)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [55]:
s4 = pd.concat([s1, s3])

In [56]:
pd.concat([s1, s4], axis=1)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [57]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [58]:
result = pd.concat([s1, s1, s3], keys=['one','two',
'three'])

In [59]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [60]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [61]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a',
'b', 'c'],columns=['one', 'two'])


In [62]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2),
index=['a', 'c'],columns=['three', 'four'])


In [63]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [64]:
df2

three  four
a      5     6
c      7     8

In [65]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'],
        names=['upper', 'lower'])

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [66]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a',
'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b',
'd', 'a'])
df1
df2

b         d         a
0 -0.761879  0.118281 -0.276619
1  0.449807  0.105664 -1.112429

In [67]:
df1

a         b         c         d
0 -0.861246 -0.965520 -0.900112 -0.533217
1 -0.439064  0.849853 -0.690896  0.734648
2 -0.768341  0.744477 -0.818002 -0.315826

In [68]:
df2

b         d         a
0 -0.761879  0.118281 -0.276619
1  0.449807  0.105664 -1.112429

In [69]:
pd.concat([df1, df2], ignore_index=True)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0 -0.861246 -0.965520 -0.900112 -0.533217
1 -0.439064  0.849853 -0.690896  0.734648
2 -0.768341  0.744477 -0.818002 -0.315826
3 -0.276619 -0.761879       NaN  0.118281
4 -1.112429  0.449807       NaN  0.105664

In [70]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
             index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
       index=['f', 'e', 'd', 'c', 'b', 'a'])

In [71]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [72]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [73]:
# 如果a等于null，就使用b的值
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, 5. ])

In [80]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                 index=pd.Index(['Ohio','Colorado'],
name='state'),
                    columns=pd.Index(['one', 'two',
'three'],
                 name='number'))


In [81]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [83]:
result = data.stack()

In [84]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [85]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [86]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5