In [1]:
import numpy as np

In [2]:
import numpy as np
print(np.__version__)
np.show_config()

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
y = np.zeros(10)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [11]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [13]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.77166022 0.36161787 0.54668696]
  [0.77256565 0.94919913 0.50308707]
  [0.78761293 0.48246425 0.91839485]]

 [[0.69172241 0.30596084 0.7075286 ]
  [0.56757256 0.2884938  0.59689796]
  [0.18284915 0.09054843 0.47538411]]

 [[0.00426309 0.97924864 0.20672974]
  [0.89312446 0.6288945  0.79423377]
  [0.99812629 0.25486888 0.72218768]]]


In [15]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.04654424317204375 0.9919689488731693


In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [21]:
np.inf > np.nan


False

In [22]:
np.nan - np.nan


nan

In [23]:

0.3 == 3 * 0.1

False

In [24]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [25]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [27]:
# 是重复数组的意思
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[1.         0.62111954 0.04451231 0.82156589 0.27683709]
 [0.78521835 0.54787401 0.40571164 0.51783134 0.89160334]
 [0.8902299  0.89538012 0.48544769 0.66241214 0.94977069]
 [0.28288887 0.55739242 0.62331825 0.40594413 0.        ]
 [0.01924617 0.28793684 0.73990513 0.16950839 0.16223216]]


In [29]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [30]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [31]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [33]:
print(sum(range(5),-1))

10


In [34]:
from numpy import *
print(sum(range(5),-1))

10


In [35]:
Z = np.arange(5)
Z ** Z  # legal

array([  1,   1,   4,  27, 256])

In [39]:
Z = np.arange(5)
2 <<Z

array([ 2,  4,  8, 16, 32])

In [40]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [41]:
Z = np.arange(5)
1j*Z   # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [42]:
 Z = np.arange(5)
Z/1/1   # legal

array([0., 1., 2., 3., 4.])

In [43]:
Z = np.arange(5)
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
print(np.array(0) / np.array(0))

nan


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [45]:
print(np.array(0) // np.array(0))

0


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [46]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


In [47]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  7.  -8.  -4.  -3.   9.  10.   3.   7.  10. -10.]


In [52]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

[9 2 3 2 2 1 3 8 5 3]
[5 4 9 3 5 3 9 4 7 5]
[3 5 9]


In [53]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [55]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-24
Today is 2019-06-25
Tomorrow is 2019-06-26


In [56]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [57]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [58]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [61]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [62]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.15399558 0.20928689 0.33129833 0.47409229 0.56067434 0.56125339
 0.78450381 0.80215277 0.80321177 0.99143017]


In [63]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [64]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [65]:
# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [66]:
# 使用如下过程实现
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [67]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.96286317 1.32086358 0.15169997 0.64687806 0.98838682 1.21401562
 0.91376947 0.89822491 0.81362227 1.00975371]
[0.36131677 0.71378643 0.87410289 1.14428691 0.35492935 0.78155081
 1.36159351 0.92909603 0.65000988 0.26062587]


In [68]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.62755631 0.48871066 0.         0.85373261 0.19684608 0.09598841
 0.04058297 0.13223475 0.49459261 0.40879887]


In [69]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [82]:
X = np.arange(8)
Y = X + 0.5
print(Y)
C =  np.subtract(X, Y)
C=np.outer(X,Y)
print(C)

[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
[[ 0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5]
 [ 1.   3.   5.   7.   9.  11.  13.  15. ]
 [ 1.5  4.5  7.5 10.5 13.5 16.5 19.5 22.5]
 [ 2.   6.  10.  14.  18.  22.  26.  30. ]
 [ 2.5  7.5 12.5 17.5 22.5 27.5 32.5 37.5]
 [ 3.   9.  15.  21.  27.  33.  39.  45. ]
 [ 3.5 10.5 17.5 24.5 31.5 38.5 45.5 52.5]]


In [83]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [84]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [85]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

4


In [4]:
Z = np.zeros(10, detype={}])
print(Z)

NameError: name 'np' is not defined

In [24]:
import numpy as np
Z = np.zeros( [('position', [('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

TypeError: 'tuple' object cannot be interpreted as an integer

In [26]:
import numpy as np
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(X,Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.66451744 0.51548435 0.99952395 0.03659224 0.98524947 0.68045148
  0.91091987 0.66376596 0.9517022  0.92699782]] [[0.81757325 0.11294259 0.96529629 0.80253326 0.09515122 0.40219163
  0.99411623 0.90585469 0.79696066 0.27966979]]


In [22]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

ModuleNotFoundError: No module named 'scipy'

In [27]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [29]:
Z = np.arange(9).reshape(3,3)
# for index, value in np.ndenumerate(Z):
#     print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [35]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
# print(X,Y)
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [36]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
X = np.random.rand(5, 10)
# Recent versions of numpy
print(X)
print(X.mean(axis=1, keepdims=True))
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.13154047 0.3794261  0.57562791 0.35155539 0.43247929 0.97262974
  0.95498061 0.10233956 0.60217478 0.68954185]
 [0.12135205 0.63974508 0.41146521 0.68356734 0.0112595  0.83574168
  0.4153171  0.49502855 0.64191564 0.84900274]
 [0.05220708 0.69214107 0.18156541 0.46832652 0.95061507 0.39872477
  0.40851637 0.35098099 0.08008632 0.17264709]
 [0.33601917 0.82269631 0.55815301 0.68488564 0.08161879 0.56145771
  0.94425647 0.35641618 0.32412693 0.65083696]
 [0.55744427 0.45089442 0.40542977 0.93979375 0.28962847 0.02142271
  0.26985346 0.87917421 0.51419481 0.95288582]]
[[0.51922957]
 [0.51043949]
 [0.37558107]
 [0.53204672]
 [0.52807217]]
[[-0.3876891  -0.13980347  0.05639834 -0.16767418 -0.08675028  0.45340017
   0.43575103 -0.41689001  0.08294521  0.17031228]
 [-0.38908744  0.12930559 -0.09897428  0.17312785 -0.49917999  0.32530219
  -0.09512239 -0.01541094  0.13147615  0.33856325]
 [-0.32337399  0.31656    -0.19401566  0.09274545  0.575034    0.0231437
   0.0329353  -0.02460008 -0.2

In [41]:
X = np.array[]
Y = X - X.mean(axis=1).reshape(-1, 1)
print (Y)

[[0.4758587 ]
 [0.320684  ]
 [0.667597  ]
 [0.51984655]
 [0.61897851]]
[[-0.03008181 -0.37926713  0.44147952  0.17835582  0.40871111 -0.43682202
  -0.45346804 -0.03278946  0.51324596 -0.20936395]
 [ 0.18783564  0.16380471 -0.11773388 -0.39944069  0.04423963  0.13577786
   0.27221106 -0.09620507 -0.14988777 -0.04060148]
 [-0.3784608  -0.22107324 -0.28701475 -0.04625204  0.31296195  0.33036793
   0.03528884 -0.13698058  0.43069937 -0.03953669]
 [-0.19359978 -0.46296308  0.01486342  0.26122466  0.08775513 -0.39945843
   0.21594561  0.43031234 -0.18188911  0.22780924]
 [-0.19576586 -0.29475273  0.17663595  0.08551989  0.06537434  0.37727526
   0.08848326  0.29328734 -0.43999471 -0.15606274]]


In [42]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.float)
print(d)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [43]:
x=d.mean(axis=0)
print(x)

[5. 6. 7. 8.]


In [44]:
print(x.reshape(-1,1))

[[5.]
 [6.]
 [7.]
 [8.]]


In [45]:
d-x

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [46]:
d-x.reshape(-1,1)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [53]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print(Z[:,1])
print(Z[:,1].argsort())
print (Z[Z[:,1].argsort()])

[[3 7 3]
 [8 6 6]
 [9 6 1]]
[7 6 6]
[1 2 0]
[[8 6 6]
 [9 6 1]
 [3 7 3]]


In [57]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
print(np.abs(Z - z).argmin())
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

[0.75203137 0.63907971 0.3781661  0.59364118 0.18032059 0.74822066
 0.10871158 0.58498021 0.13197886 0.03227886]
7
0.5849802128162231


In [60]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [2]:
import numpy as np
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [3]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 5. 1. 5. 2. 3. 4. 1. 4.]
